name: Build and Test with deps

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout VSL
      uses: actions/checkout@v2
      with:
        path: vsl
    - name: Build V and symlink
      run: |
        make
        ./v symlink
    - name: V doctor
      run: v doctor
    - name: Install VSL and dependencies
      run: |
        sudo apt-get install --quiet -y --no-install-recommends gfortran liblapacke-dev libopenblas-dev libgc
    - name: Move VSL source code to V Modules
      run: mv ./vsl ~/.vmodules
    - name: Execute Tests using Pure V Backend
      run: ~/.vmodules/vsl/bin/test
    - name: Execute Tests using Pure V Backend with Pure V Math
      run: ~/.vmodules/vsl/bin/test --use-cblas
    - name: Execute Tests using Pure V Backend and Garbage Collection enabled
      run: ~/.vmodules/vsl/bin/test --use-gc boehm
    - name: Execute Tests using Pure V Backend with Pure V Math and Garbage Collection enabled
      run: ~/.vmodules/vsl/bin/test --use-cblas --use-gc boehm

  # macos:
  #   runs-on: macos-latest
  #   steps:
  #   - name: Checkout Latest V
  #     uses: actions/checkout@v2
  #     with:
  #       repository: vlang/v
  #   - name: Checkout VSL
  #     uses: actions/checkout@v2
  #     with:
  #       path: vsl
  #   - name: Build V and symlink
  #     run: |
  #       make
  #       ./v symlink
  #   - name: V doctor
  #     run: v doctor
  #   - name: Install VSL and dependencies
  #     run: |
  #       brew install openblas
  #   - name: Move VSL source code to V Modules
  #     run: mv ./vsl ~/.vmodules
  #   - name: Execute Tests using Pure V Backend
  #     run: ~/.vmodules/vsl/bin/test
  #   - name: Execute Tests using Pure V Backend with Pure V Math
  #     run: ~/.vmodules/vsl/bin/test --use-cblas
