name: Build and Test with deps

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "31 1,12 * * *"

  push:
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]

    steps:
      - name: Checkout Latest V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout VSL
        uses: actions/checkout@v2
        with:
          path: vsl
      - name: Build V and symlink
        run: |
          make
          ./v symlink
      - name: V doctor
        run: v doctor
      - name: Install VSL and dependencies
        run: |
          sudo apt-get install --quiet -y --no-install-recommends gfortran liblapacke-dev libopenblas-dev libgc-dev
      - name: Move VSL source code to V Modules
        run: mv ./vsl ~/.vmodules
      - name: Execute Tests using Pure V Backend
        run: ~/.vmodules/vsl/bin/test
      - name: Execute Tests using Pure V Backend with Pure C Blas
        if: ${{ matrix.os }} != "ubuntu-18.04"
        run: ~/.vmodules/vsl/bin/test --use-cblas
      - name: Execute Tests using Pure V Backend and Garbage Collection enabled
        run: ~/.vmodules/vsl/bin/test --use-gc boehm
      - name: Execute Tests using Pure V Backend with Pure C Blas and Garbage Collection enabled
        run: ~/.vmodules/vsl/bin/test --use-cblas --use-gc boehm
        if: ${{ matrix.os }} != "ubuntu-18.04"
