name: Deploy Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy-docs:
    concurrency: deployment
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout VSL
        uses: actions/checkout@v2
        with:
          path: vsl

      - name: Setup V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: V doctor
        run: v doctor

      - name: Build docs
        run: |
          rm -f ./vsl/README.md
          mv ./vsl/static/DOCS.md ./vsl/README.md
          v doc -m -f html ./vsl
          mv ./vsl/_docs/vsl.html ./vsl/_docs/index.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vsl/_docs/
