name: Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout VSL
        uses: actions/checkout@v2

      - name: Setup V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: V doctor
        run: v doctor

      - name: Build docs
        run: |
          rm -f ./README.md
          mv ./static/DOCS.md ./README.md
          v doc -m -f html/
          mv ./_docs.html ./_docs/index.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_docs/
