name: Validate Docs

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout VSL
        uses: actions/checkout@v2
        with:
          path: vsl

      - name: Setup V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: V doctor
        run: v doctor

      - name: Install VSL and dependencies
        run: |
          sudo apt-get install --quiet -y --no-install-recommends gfortran liblapacke-dev libopenblas-dev libgc-dev

      - name: Copy VSL source code to V Modules
        run: cp -rf ./vsl ~/.vmodules

      - name: Validate docs
        run: |
          cd ./vsl
          v check-md .
