name: Periodic Check

on:
  schedule:
    - cron:  '31 1,12 * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout VSL
      uses: actions/checkout@v2
      with:
        path: vsl
    - name: Build V
      run: |
        make
        sudo ./v symlink
    - name: V doctor
      run: v doctor
    - name: Install VSL and dependencies
      run: |
        ln -s vsl ~/.vmodules/vsl
        sudo apt-get install --quiet -y --no-install-recommends gfortran liblapacke-dev libopenblas-dev
    - name: Execute Tests using Pure V Backend with Vlib Math
      run: cd vsl; ./bin/test
    - name: Execute Tests using Pure V Backend with Pure V Math
      run: cd vsl; ./bin/test --use-vmath
    - name: Execute Tests using Open BLAS Backend
      run: cd vsl; ./bin/test --use-cblas
    - name: Execute Tests using Open BLAS Backend and Pure V Math
      run: cd vsl; ./bin/test --use-vmath --use-cblas
